#!/bin/bash

search_string="https://www.google.com/search?q="

for var in "$@"
do
    search_string="${search_string}${var}+"
done

# Remove unnecessary plus sign at the end
search_string=${search_string::-1}

firefox --new-tab $search_string